export const CHANGE_SIZE_TYPE = 'CHANGE_SIZE_TYPE';
export const CHANGE_PROPORTION = 'CHANGE_PROPORTION';
export const GET_COFFEE_DATA = 'GET_COFFEE_DATA';


export const WATCH_COFFEE_DATA_SAGA = 'WATCH_COFFEE_DATA_SAGA';